// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Returns Md Najish Anjum's public profile info (name, title, tagline, and social/portfolio links).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Md Najish Anjum",
      title: "AI/ML Developer & Full Stack Builder",
      tagline: "Build Ajinava Edge \xB7 I Lead Team ILM Tech",
      links: {
        portfolio: "https://najish-anjum-portfolio.vercel.app/",
        github: "https://github.com/Najishanjum",
        linkedin: "https://www.linkedin.com/in/md-najish-anjum-044078328",
        workWithMe: "https://teamilmtech.site",
        community: "https://chat.whatsapp.com/IJw256xuepP956JsufMY6g",
        email: "najishanjum058@gmail.com"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/get-visitor-count.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
var get_visitor_count_default = defineTool2({
  name: "get_visitor_count",
  title: "Get visitor count",
  description: "Returns the total number of visits to the profile card.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { count, error } = await supabase.from("page_visits").select("*", { count: "exact", head: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const total = count ?? 0;
    return {
      content: [{ type: "text", text: `Total visits: ${total}` }],
      structuredContent: { total }
    };
  }
});

// src/lib/mcp/tools/get-ist-time.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_ist_time_default = defineTool3({
  name: "get_ist_time",
  title: "Get IST time",
  description: "Returns the current date and time in India Standard Time (Asia/Kolkata, UTC+5:30).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: () => {
    const now = /* @__PURE__ */ new Date();
    const formatted = new Intl.DateTimeFormat("en-IN", {
      timeZone: "Asia/Kolkata",
      dateStyle: "full",
      timeStyle: "long",
      hour12: true
    }).format(now);
    const payload = { iso: now.toISOString(), ist: formatted, timezone: "Asia/Kolkata", utcOffset: "+05:30" };
    return {
      content: [{ type: "text", text: formatted }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "najish-profile-mcp",
  title: "Md Najish Anjum \xB7 Profile MCP",
  version: "0.1.0",
  instructions: "Public tools for Md Najish Anjum's profile card. Use `get_profile` for identity and links, `get_visitor_count` for total visits, and `get_ist_time` for current India Standard Time.",
  tools: [get_profile_default, get_visitor_count_default, get_ist_time_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
